$(document).ready(function(){
    $("#toggle1").click(function(){
      $(".testP1").toggle();
      $(".icon1").toggle();
      $(".icon-minus1").toggle();
    });
  });
  $(document).ready(function(){
    $("#toggle2").click(function(){
      $(".testP2").toggle();
      $(".icon2").toggle();
      $(".icon-minus2").toggle();
    });
  });
  $(document).ready(function(){
    $("#toggle3").click(function(){
      $(".testP3").toggle();
      $(".icon3").toggle();
      $(".icon-minus3").toggle();
    });
  });
